### ISSUE TITLE
More detailed information

### ISSUE THREAD

**Issue by 2226123114** [mathCederbladh/Heat-Storage-In-Buildings---Code#1]
Dear author, is there any more detailed document about your work, i really want to learn about it. Thanks a lot!

**Comment by mathCederbladh** [comment]
Hi! As soon as the report is published we will link to it here, I expect it should be available sometime next week :)

**Comment by 2226123114** [comment]
with best wishes!

**Comment by mathCederbladh** [comment]
The report is now linked in the read me :)
